var OH = require('../')
var test = require('tape')

test('creates new box', function (t) {
  var box = OH.create()
  t.strictEqual(box.first, 0)
  t.strictEqual(box.last, -1)
  t.deepEqual(box.vals, {})
  t.deepEqual(box.indexes, {})
  t.end()
})

test('push, unshift, pop, shift, get, getIndex, length', function (t) {
  var h = OH.create()
  h.push('c', 'C')
  h.push('d', 'D')
  t.strictEqual(h.length(), 2)
  h.unshift('b', 'B')
  h.unshift('a', 'A')
  t.strictEqual(h.length(), 4)
  t.strictEqual(h.getIndex('a'), 0)
  t.strictEqual(h.getIndex('b'), 1)
  t.strictEqual(h.getIndex('c'), 2)
  t.strictEqual(h.getIndex('d'), 3)
  t.strictEqual(h.get('a'), 'A')
  t.strictEqual(h.get('b'), 'B')
  t.strictEqual(h.get('c'), 'C')
  t.strictEqual(h.get('d'), 'D')

  var d = h.pop()
  var a = h.shift()
  t.strictEqual(h.length(), 2)
  t.strictEqual(d, 'D')
  t.strictEqual(a, 'A')

  h.unshift('a', 'A')
  h.push('d', 'D')
  t.strictEqual(h.length(), 4)
  t.strictEqual(h.getIndex('a'), 0)
  t.strictEqual(h.getIndex('b'), 1)
  t.strictEqual(h.getIndex('c'), 2)
  t.strictEqual(h.getIndex('d'), 3)
  t.strictEqual(h.get('a'), 'A')
  t.strictEqual(h.get('b'), 'B')
  t.strictEqual(h.get('c'), 'C')
  t.strictEqual(h.get('d'), 'D')
  t.end()
})

test('set', function (t) {
  var h = OH.create()
  h.push('x', 'X')
  h.set('x', 'Y')
  t.strictEqual(h.get('x'), 'Y')
  t.end()
})

test('swap', function (t) {
  var box = OH.create()
  box.push('x', 'a')
  box.push('y', 'b')
  t.strictEqual(box.getIndex('x'), 0)
  t.strictEqual(box.getIndex('y'), 1)
  box.swap('x', 'y')
  t.strictEqual(box.getIndex('x'), 1)
  t.strictEqual(box.getIndex('y'), 0)
  t.end()
})

test('remove', function (t) {
  var box = OH.create()
  box.push('x', 'a')
  box.push('y', 'b')
  box.push('z', 'c')
  box.push('q', 'd')
  box.remove('y')
  t.strictEqual(box.getIndex('x'), 0, 'x index')
  t.strictEqual(box.getIndex('z'), 1, 'y index')
  t.strictEqual(box.getIndex('q'), 2, 'q index')
  t.end()
})
